version: v2
    
tasks:    
  build-image:
    steps:
    - checkout
    - docker/build:
        image: saurabh3460/yii2-prod
        tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
        push: true
      if: branch == "ec2"
    - docker/build:
        image: saurabh3460/yii2-stage
        tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
        push: true
      if: branch == "stage"
    - workspace/persist:
        paths: [deploy]

  deploy:
    depends: [build-image]
    variables:
    - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    steps:

    - commands:
      - |
        if [[ $CI_REPO_BRANCH == "ec2" ]]; then

            ssh -v ubuntu@cloud-native.me <<'ENDSSH'
                  docker pull saurabh3460/yii2-prod:latest
                  docker stop yii2-prod 
                  docker rm yii2-prod
                  docker run -d --name yii2-prod saurabh3460/yii2-prod:latest
                ENDSSH

          elif [[ $CI_REPO_BRANCH == "stage" ]]; then
                  
            ssh -v ubuntu@cloud-native.me <<'ENDSSH'
                  docker pull saurabh3460/yii2-stage:latest
                  docker stop yii2-stage 
                  docker rm yii2-stage
                  docker run -d --name yii2-stage saurabh3460/yii2-stage:latest
                ENDSSH

          else
              echo "Unsupported release branch: $CI_REPO_BRANCH "
              exit 1
        fi

    # - commands:
    #   - |
    #     ssh -v ubuntu@ec2.com <<'ENDSSH'
    #       docker pull 

trigger:
  when: branch in ("stage", "main", "ec2")
