version: v2
    
tasks:    
  deploy:
    steps:
    - checkout
    - run: |
        ls ~/.ssh
        if [[ $CI_REPO_BRANCH == "ec2-docker-voloum" ]]; then

          rsync -a ./* ubuntu@34.230.69.26:/home/ubuntu/hh-dev

        elif [[ $CI_REPO_BRANCH == "stage" ]]; then
          
          rsync -a ./* ubuntu@<stage-vm-ip>:/home/ubuntu/hh-dev

        else
              echo "Unsupported release branch: $CI_REPO_BRANCH "
              exit 1
        fi

trigger:
  when: branch in ("stage", "main", "ec2-docker-voloum", "system-prod")
