version: v2

tasks:    
  deploy:
    steps:
    - commands:
      - |
        ls ~/.kube/
        cat ~/.kube/config
        echo $KUBECONFIG
        kubectl config use-context do-sfo3-kait-stage-k8s
