version: v2
    
tasks:    
  # build-image:
  #   steps:
  #   - checkout
  #   - docker/build:
  #       image: saurabh3460/yii2-prod
  #       tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
  #       push: true
  #     if: branch == "ec2-docker-voloum"
  #   - docker/build:
  #       image: saurabh3460/yii2-stage
  #       tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
  #       push: true
  #     if: branch == "stage"

  deploy:
    steps:
    - checkout
    - run: |
        if [[ $CI_REPO_BRANCH == "ec2-docker-voloum" ]]; then

        # scp -r ./* ubuntu@34.230.69.26:/home/ubuntu/hh-dev
        rsync -a ./* ubuntu@34.230.69.26:/home/ubuntu/hh-dev
        # ssh ubuntu@34.230.69.26 <<'EOF'
        #   docker pull saurabh3460/yii2-prod:latest
        #   docker stop yii2-prod
        #   docker run -d --rm --name yii2-prod -p 80:80 saurabh3460/yii2-prod:latest

        #   if [ -n "$(docker images -f 'dangling=true' -q)" ]; then 
        #     # remove the dangling images
        #     docker rmi $(docker images -f 'dangling=true' -q)
        #   fi
        # EOF

        elif [[ $CI_REPO_BRANCH == "stage" ]]; then
                  
        ssh ubuntu@34.230.69.26 <<'EOF'
          docker pull saurabh3460/yii2-stage:latest
          docker stop yii2-stage
          docker run -d --rm --name yii2-stage -p 8080:80 saurabh3460/yii2-stage:latest
          if [ -n "$(docker images -f 'dangling=true' -q)" ]; then 
            # remove the dangling images
            docker rmi $(docker images -f 'dangling=true' -q)
          fi
        EOF

        else
              echo "Unsupported release branch: $CI_REPO_BRANCH "
              exit 1
        fi

trigger:
  when: branch in ("stage", "main", "ec2-docker-voloum", "system-prod")
