version: v2

# global:
#   runner:
#     containers:
#       - image: python

tasks:    
  deploy:
    variables:
    - APP_NAME=cloudmey
    # - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    steps:
    - checkout
    - commands:
      - |
        ls
        sudo apt update
        sudo apt-get install php-curl php-mbstring php-zip php-dom
        pip install PyYAML==5.3.1
        pip install awsebcli --upgrade --user
        eb --version
        eb init $ENV_NAME --platform PHP --region $AWS_DEFAULT_REGION --quiet
        eb list
        
      
  # build-image:
  #   steps:
  #   - checkout
  #   - commands: 
  #     - helm lint $HELM_CHART
  #   - docker/build:
  #       image: registry.digitalocean.com/cloudmeyrazo/newprdgamesmela
  #       tags: ["latest", "${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}"]
  #       push: true
  #     if: branch == "prod"

  #   - docker/build:
  #       image: registry.digitalocean.com/cloudmeyrazo/newstggamesmela
  #       tags: ["latest", "${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}"]
  #       push: true
  #     if: branch == "stage"

  #   - workspace/persist:
  #       paths: [deploy]


# trigger:
  # when: branch in ("stage", "prod")