version: v2

global:
  runner:
    containers:
      - image: python

tasks:    
  deploy:
    variables:
    - APP_NAME=cloudmey
    # - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    steps:
    - checkout
    - commands:
      - |
        pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==6.0
        pip install awsebcli --upgrade --user
        eb --version
        # sudo pip3 install virtualenv
        # # composer create-project --prefer-dist yiisoft/yii2-app-basic basic
        # git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
        # python3 ./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py

  # build-image:
  #   steps:
  #   - checkout
  #   - commands: 
  #     - helm lint $HELM_CHART
  #   - docker/build:
  #       image: registry.digitalocean.com/cloudmeyrazo/newprdgamesmela
  #       tags: ["latest", "${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}"]
  #       push: true
  #     if: branch == "prod"

  #   - docker/build:
  #       image: registry.digitalocean.com/cloudmeyrazo/newstggamesmela
  #       tags: ["latest", "${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}"]
  #       push: true
  #     if: branch == "stage"

  #   - workspace/persist:
  #       paths: [deploy]


# trigger:
  # when: branch in ("stage", "prod")